[project]
name = "link-shortener"
revision = "1.0"

[providers]
local = "dotenv://.env"
vault = "vault://secrets.scottylabs.org/secret"

[profiles.ci.defaults]
required = false

[profiles.default]
KEYCLOAK_URL = { description = "Keycloak base URL" }
KEYCLOAK_REALM = { description = "Keycloak realm name" }
OIDC_CLIENT_ID = { description = "OIDC client ID" }
OIDC_CLIENT_SECRET = { description = "OIDC client secret" }
OAUTH_RELAY_URL = { description = "OAuth relay callback URL" }
PROJECT_GROUP = { description = "Keycloak project group path" }
PROJECT_ADMIN_GROUP = { description = "Keycloak project admin group path" }

[profiles.prod]

[profiles.staging]

[profiles.preview]

[profiles.dev.defaults]
providers = ["vault"]

[profiles.dev]
